# Generated by Django 4.2.9 on 2024-02-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auction_auctionitem_depositrecord_browserecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='balance',
            field=models.PositiveIntegerField(default=1000, verbose_name='余额'),
        ),
    ]
