# Generated by Django 4.2.9 on 2024-02-04 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userinfo_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='cover',
            field=models.FileField(max_length=128, upload_to='', verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='cover',
            field=models.FileField(max_length=128, upload_to='', verbose_name='拍品封面'),
        ),
        migrations.AlterField(
            model_name='auctionitemimage',
            name='img',
            field=models.FileField(max_length=64, upload_to='', verbose_name='详细图'),
        ),
        migrations.CreateModel(
            name='AuctionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview_task', models.CharField(max_length=64, verbose_name='Celery预展任务ID')),
                ('auction_task', models.CharField(max_length=64, verbose_name='Celery拍卖任务ID')),
                ('auction_end_task', models.CharField(max_length=64, verbose_name='Celery拍卖结束任务ID')),
                ('auction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.auction', verbose_name='专场')),
            ],
        ),
    ]
