# Generated by Django 4.2.9 on 2024-02-04 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_auction_cover_alter_auctionitem_cover_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, '未支付'), (2, '待收货'), (3, '已完成'), (4, '逾期未支付')], verbose_name='状态')),
                ('uid', models.CharField(max_length=64, verbose_name='流水号')),
                ('price', models.PositiveIntegerField(verbose_name='出价')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('twenty_four_task_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='24小时后定时任务')),
                ('deposit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.depositrecord', verbose_name='保证金')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.auctionitem', verbose_name='拍品')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.userinfo', verbose_name='用户')),
            ],
        ),
        migrations.CreateModel(
            name='DepositRefundRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=64, verbose_name='流水号')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, '待退款'), (2, '退款成功')], verbose_name='状态')),
                ('amount', models.PositiveIntegerField(verbose_name='退款金额')),
                ('deposit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.depositrecord', verbose_name='保证金')),
            ],
        ),
        migrations.CreateModel(
            name='DepositDeduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='金额')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.order', verbose_name='订单')),
            ],
        ),
    ]
