# Generated by Django 4.2.9 on 2024-02-05 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_order_depositrefundrecord_depositdeduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(1, '未开始'), (2, '领取中'), (3, '已结束')], default=1, verbose_name='状态')),
                ('title', models.CharField(max_length=32, verbose_name='优惠券名称')),
                ('money', models.PositiveIntegerField(default=200, verbose_name='抵扣金额')),
                ('count', models.PositiveIntegerField(default=100, verbose_name='创建数量')),
                ('apply_count', models.PositiveIntegerField(default=0, verbose_name='已申请数量')),
                ('apply_start_date', models.DateTimeField(verbose_name='开始领取时间')),
                ('apply_stop_date', models.DateTimeField(verbose_name='领取结束时间')),
                ('apply_start_task_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='celery任务ID')),
                ('apply_stop_task_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='celery任务ID')),
                ('deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('auction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.auction', verbose_name='专场')),
            ],
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(1, '未使用'), (2, '已使用'), (3, '已过期')], default=1, verbose_name='状态')),
                ('coupon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.coupon', verbose_name='优惠券')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.order', verbose_name='订单')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.userinfo', verbose_name='用户')),
            ],
        ),
    ]
